HaliteChallenge/Halite

website/organizationWhitelist.txt

It seems the program identify the email address by splitting by @, rather than check ends with same string, so add more related email addresses. Feel free to reject me if I'm wrong.

Add Harvard email addresses

---

airesources/C++/runGame.bat

With "./" in there you get an error saying "'.' is not recognized as an internal or external command,"

Fix runGame.bat to work on Windows.

---

environment/make.bat

... why?
Simply because compiling in the same directory is hard if i have to copy the tclap/ directory in another directory called ../environment that i need to create. Or, the other way around: This way it's simpler. Dont you think? :smile:
EDIT: To clarify: You give out on the website a ZIP containing ONLY the environment directory contents, but not the directory itself. This way you can avoid having it.
The executable name-change is made there because nothing in the other sources directs to a "environment.exe" or the linux binarys; And here we can compile and copy without even renaming it(Any executable is called halite or halite.exe in any source... the Makefile also points to hailte ELF-Binary)
EDIT2: This one: https://halite.io/downloads/environment/HaliteEnvironment-Source.zip

change -I ../environment  to . in make.bat

---

website/basics_improve_random.php

I've just noticed there's a link to the "Improving the Random Bot" code. I've updated that link to point to the new gist.

Change link to Python code gist

---

airesources/Ruby/networking.rb

Values for production were stored as a 2d array of values, but the GameMap initializer was expecting a flattened array.
This currently prevents using a site's production value in the bots.

Fix production values used when initializing a GameMap in the Ruby Kit

---

airesources/Rust/src/hlt/types.rs

Adding a `get_site_ref` method to `types.rs` as most calls to `get_site` do not require a mutable reference. As only one mutable reference is allowed in rust this would prevent multiple calls of `get_site` as the reference would continue to exist in the scope.
This PR's method allows the developer to ask for a immutable reference, which is what they want most of the time, in order to avoid problems with the Rust Borrow Checker.

Rust: adding get_site_ref method to types in starter package

---

worker/compiler.py

#217 exposed some issues with Java submissions:
* Compilation may seem to succeed when it actually doesn't
* The encoding used when calling `javac` is environment-dependent
As Java files doesn't _have_ to produce class files with the same name as the file itself, we cannot use `out_ext` as it would create false positives. However,  we do know that `MyBot.class` will exist, and we can check for that one.
The Docker environment causes the javac compiler to run with ASCII encoding, which causes trouble with... non-ASCII values in source code. The typical default encoding for Javac on more or less all system these days is UTF-8, which is also backwards compatible with ASCII. Therefore it should be fine to set UTF-8 as default encoding for javac.
I haven't tested this with the Python code in a …

Let javac use UTF-8 encoding, and look for MyBot.class

---

airesources/OCaml/halite.ml

Apologies, I discovered a bug in the movement directions today for the OCaml starter.

bugfix for get_location directions

---

website/api/manager/ManagerAPI.php

As suggested here: http://forums.halite.io/t/faster-ranking-in-matchmaking/466
Open Questions:
1. there is no guarantee that anyone will have a mu "near enough" to us to match against, what should we do about this?
2. Do we always want to use sigma? or do we just want to use it for the first x games? or until our sigma is low?
3. should we change the query to look for other bots with a low sigma?

Finding matches now uses mu instead of rank

---

environment/networking/Networking.cpp
environment/networking/Networking.hpp

Right now when the game environment `halite` is terminated (say by `SIGINT`), it leaves all the spawned bots behind.
To see this using the C++ starter package: run a game like `./halite -d "40 40" "./MyBot.o" "./RandomBot.o"`, press Ctrl-C while the game is still running (gotta be quick to catch it!), and check `ps -ef | grep MyBot.o`.
This commit fixes this issue for Linux. (No idea about Windows, as reported in #175.)
It installs a `PR_SET_PDEATHSIG` signal in each spawn child process. This ensures that all bots spawned by the game environment are properly killed when the environment itself is interrupted / terminated.

Install a parent death signal in child processes

---

website/organizationWhitelist.txt

Changed organization address from kuleuven.be to student.kuleuven.be.

Fixed KU Leuven organization

---

environment/networking/Networking.cpp
environment/networking/Networking.hpp

`sys/prctl` is only supported on linux. Other platforms will not have
children terminated when the parent dies.

Fix building Halite environment on Mac

---

website/script/visualizer.js

Currently the visualizer draws frames continuously without intermittence. This drives my poor laptop CPU to 100% usage and the fan kicks in shortly afterwards. I can actually smell the pleasant aroma of overheating plastics in under 10 seconds if I forget to close the visualizer tab.
This pull request puts a cap on the refresh rate to 60 FPS through a simple "setTimeout" delay. To further reduce CPU load, the refresh rate is capped down to 10 FPS when the game is paused with no key being pressed.

Set a cap on visualizer FPS to reduce load

---

environment/core/Halite.cpp
environment/core/Halite.hpp
environment/main.cpp

Allow just a single bot to be specified when launching game environment, which enables single-player mode.  Count productive_squares_remaining every turn, and when in single-player mode, continue game loop while productive_squares_remaining > 0.  Fame and glory to those that completely mine a given board in the fewest frames.

Enable Halite single-player mode

---

environment/core/Halite.cpp
environment/core/Halite.hpp
environment/main.cpp

Takes -n command line argument to create a map "as if" there were n players.  If n is specified, single player mode is also required.  This feature allows single-player mode users to play the same maps seen in multi-player competition.

Enable multi-player maps in single player mode.  

---

environment/networking/Networking.cpp

Without this patch, i get this error on FreeBSD 11 / clang 3.8.0:
> networking/Networking.cpp:261:17: error: cast from pointer to smaller type 'pid_t' (aka 'int') loses information
pid_t pid = (pid_t)NULL;
^~~~~~~~~~~
1 error generated.

Remove cast for pid variable

---

environment/core/Halite.cpp
environment/core/Halite.hpp
environment/main.cpp

in both verbose and quiet.  Last_frame_alive reports how far into the game each bot survives ... more color than just rank finish.  Also, it's the score for single player mode.

Record and report last_frame_alive for each bot

---

worker/compiler.py

This will instruct the compiler to reference the System.* libraries available on a typical dotnet framework installation

C# Reference available System.* libraries

---

website/script/status.js

This marks the times returned from the server as UTC timezone so that the correct period since last communication with a worker is shown.

Force status page to parse times as UTC.

---

website/basics_intro_halite.php

In Mac OSX running `$ . runGame.sh` will not work, there needs to be a '/' inserted as follows `$./runGame.sh`.

Update instructions to run halite at the terminal

---

airesources/Clojure/runGame.bat

Fix 1 adds a 'call' command before the lein uberjar command so that the runGame.bat does not stop after the lein command.
Fix 2 removes the backslash in front of halite.exe so that windows will try to run it out of the current folder.

Two fixes for windows runGame.bat in the clojure starter package

---

website/sql/schema.sql

The altar table statement is:
ALTER TABLE GameUser ADD PRIMARY KEY (gameID, userID);
On a local test setup with 1000 users and 70000 games this reduces the game api query on a user page from 760ms to 5ms, and on the recent_games page from 2 seconds to 100ms. Currently the recent_games request on the live server typically takes between 2.5-3.5 seconds.

Add primary key to GameUser table.

---

website/api/manager/ManagerAPI.php

Note that this won't immediately stop the runaway from getting games, but the runaway should immediately start winning games. This should bring things back into balance fairly soon.
The following is my monologue from discord where I discover and go through the problem:
> Somehow Sametine manages to come in last for every single game, even though pretty much all his opponents now are immediate crashers. https://halite.io/user.php?userID=4246
This has driven his mu down to -25.56 which in itself isn't necessarily a problem. But since the next closest mu is around -1.9 there are no opponents anywhere near his mu which means his sigma has greatly increased since the system has no idea how far down his mu should be.
So his sigma is now at 2.66
That is a problem
fresh submissions start at 2.33 …

Possible runaway crash bot fix.

---

website/script/visualizer.js

Two changes that add a bit of information to the visualizer. First when clicking on a cell in the visualizer show the move the player makes along with the strength and production. Second draw zero strength moves as a small empty box moving. This can makes it instantly clear what is happening in situations like http://forums.halite.io/t/can-anyone-explain-this-replay-to-me/392

Have the visualizer show more move information.

---

airesources/Java/Direction.java
airesources/Java/GameMap.java
airesources/Java/Location.java
airesources/Java/MyBot.java
airesources/Java/Networking.java
airesources/Java/RandomBot.java
airesources/Java/Site.java

The current implementation of the Java starter package has the disadvantage that it produces a lot of object churn mainly because the game map is re-created upon each turn. This pull request contains a modified version of the starter package which prevents the object churn by creating the game map, locations, and sites once and updating them later on.

Performance improvement for Java Starter Package: Got rid of object churn

---

website/script/visualizer.js

When toggling the graphs it changes the aspect ratio and can leave garbage on the screen in some cases on some browsers. This clears the current map and graphs before making the change.

Clear graphics before toggling extra graphs.

---

website/script/visualizer.js

This fixes the stale graphics sometimes seen when toggling the graphs on firefox.
Also removes some commented out code that was accidentally left in before.

Force a render after clearing graphics before changing graphs.

---

worker/compiler.py

The Scala langauge supports compiling both
Java and Scala, but running Javac with no file
arguments is an error. Preserve support for
combining languages by checking for no files
in a glob and returning success for that compiler.

ExternalCompiler returns success if no files to compile

---

airesources/Scala/Bot.scala
airesources/Scala/Env.scala
airesources/Scala/Grid.scala
airesources/Scala/Move.scala
airesources/Scala/MyBot.scala
airesources/Scala/RandomBot.scala

This is an important fix for the Scala starter package. It currently crashes if width/height are not equal.
Note that the Scala starter package depends on the below PR to compile correctly on the server without any .java files: https://github.com/HaliteChallenge/Halite/pull/335
Cleaned up the interface and added utilities I've found useful.

Scala starter package bug: Fix size parsing for unequal width/height

---

website/api/manager/ManagerAPI.php

This should solve a race condition when a new submission comes in after a game has already been accepted but not yet had trueskill updated. Currently the reset mu and sigma will get overwritten with old values effectively removing the reset.

Make trueskill updates dependant on numSubmissions not changing.

---

website/script/user.js

This sets the column on the user page game list to always show if the bot had an error in the corresponding game. If the page is not the logged in user then it just shows a glyphicon-exclamation-sign, otherwise it links to the error log as is currently done.
The patch also moves the error column to immediately follow the result column. This seemed to group related information and look better as well.

On the user page, always show if a bot errored in a game.

---

website/script/user.js

Follow on to PR #392 getting rid of the error column altogether and displaying it as part of the result. (See screenshot in #392)
Can close if you like the explicit column better.

Eliminate error column in user page gamelist.

---

admin/rankReset.py

This is a script to reset the ranks for the start of finals. It saves all of the current ranks and number of games by acting as if every user had resubmitted a new bot.
I've tested locally but would love to hear that someone else tested it before it is actually used live.

Script to reset all user ranks and scores.
