HaliteChallenge/Halite

airesources/Python/MyBot.py, airesources/Python/hlt.py, airesources/Python/networking.py, manager/trueskillMatchQuality.py, manager/updateTrueskill.py, manager/updateTruskill.py, website/tutorials/basic/BasicBot.py, website/tutorials/machinelearning/MattBot.py, website/tutorials/machinelearning/TrainMatt.py, website/tutorials/machinelearning/hlt.py, website/tutorials/machinelearning/networking.py, worker/backend.py, worker/compiler.py, worker/sandbox.py, worker/worker.py, worker/zip.py
To reproduce: autopep8 --in-place --verbose --pep8-passes=2000 *.py
=> PEP8 Python files, via autopep8

website/php/WebsiteAPI.php
Makes developing API integrations a lot harder...
=> Allow CORS

.travis.yml, tests/runTests.sh, worker/Dockerfile, worker/compiler.py, worker/install.sh, worker/runGame.sh
Integrates the worker tests with travis, putting the docker sandbox build on docker hub in the process.
=> Worker tests travis

.travis.yml, tests/install.sh, worker/install.sh, worker/runGame.sh
Dont merge. Will be squashed when merged.
=> Fix travis build

airesources/C++/MyBot.cpp, airesources/C++/make.bat, airesources/C++/socket_networking.hpp, airesources/Java/MyBot.java, airesources/Java/Networking.java, airesources/Java/SocketNetworking.java, airesources/Python/socket_networking.py, airesources/pipe_socket_translator.py, environment/make.bat
=> Intersocket

website/api/manager/ManagerAPI.php, worker/worker.py
=> Replay gzip

.htaccess, admin/cron/linkChecker.py, admin/md/DISASTER.md, admin/md/SPEC.md, tests/website/BotFileTest.php, website/404.php, website/advanced_replay_file.php, website/api/API.class.php, website/api/manager/ManagerAPI.php, website/api/web/WebsiteAPI.php, website/basics_intro_halite.php, website/install.sh, website/rules_game.php
=> mv bots to s3

website/api/API.class.php, website/api/manager/ManagerAPI.php, website/api/web/WebsiteAPI.php, website/script/backend.js, website/script/user.js, website/sql/schema.sql, website/user.php
In the process, contains a slight refactor of the user homepage
=> Email notifications on user homepage

website/advanced_writing_sp.php
Happy to update examples to better fit API docs if y'all prefer.
=> Update API to better fit examples

airesources/Python/MyBot.py, airesources/Python/RandomBot.py, website/basics_improve_random.php
I felt that the Python code in the starter kit could be somewhat improved. I've also refactored the "Improving the Halite Random Bot (Python 3)" section of the website. Here's my [gist](https://gist.github.com/JCGrant/5ea767bae8a725f738d75649e5f2c91a) containing the code.
By the way, this is an amazing project! Great work!
=> Refactor the Python 3 Starter Kit

website/local_visualizer.php, website/script/localVisualizer.js
I thought that having a file picker present would be convenient. Let me know what you all think/any issues with this.
=> Add file picker to local visualizer

website/organizationWhitelist.txt
[Imperial College London](https://www.imperial.ac.uk)
=> Add Imperial to organisation whitelist

airesources/Julia/MyJuliaBot.jl, airesources/Julia/RandomBot.jl, airesources/Julia/hlt.jl, airesources/Julia/networking.jl, airesources/Julia/runGame.bat, airesources/Julia/runGame.sh
=> Julia Starter Package

airesources/PHP/MyBot.php, airesources/PHP/RandomBot.php, airesources/PHP/hlt.php, airesources/PHP/networking.php, airesources/PHP/runGame.bat, airesources/PHP/runGame.sh
Initial PHP implementation (based on the Python implementation).
=> PHP Starter Package

airesources/Ruby/MyBot.rb, airesources/Ruby/RandomBot.rb, airesources/Ruby/game_map.rb, airesources/Ruby/location.rb, airesources/Ruby/move.rb, airesources/Ruby/networking.rb, airesources/Ruby/runGame.bat, airesources/Ruby/runGame.sh, airesources/Ruby/site.rb
Ruby implementation somewhat based on the Python one. 
I've stepped away from the global functions, since that's really not very nice :)
I've ran this against ruby 2.1.5 and ruby 2.3.1 (latest) successfully.
=> Ruby starter kit

website/organizationWhitelist.txt
Adding UC Berkeley's domain name to the list
=> Adding UC Berkeley

.gitignore, airesources/Haskell/halite-haskell.cabal, airesources/Haskell/lib/Halite.hs, airesources/Haskell/lib/Halite/Classes.hs, airesources/Haskell/lib/Halite/Networking.hs, airesources/Haskell/lib/Halite/Types.hs, airesources/Haskell/src/MyBot.hs, airesources/Haskell/src/RandomBot.hs
The most important features are: 
- `Networking.hs` exports only one function `communicate` with rather complicated type signature. 
- All side effects should be mentioned in type signature of `algorithm`.
Note: Although type checker tells me everything is fine, I haven't tried to play any game yet !
=> [Haskell] New interface for Starter Package

airesources/Haskell/lib/Halite/Networking.hs, airesources/Haskell/lib/Halite/Types.hs, airesources/Haskell/src/MyBot.hs, airesources/Haskell/src/RandomBot.hs
See #204 and #216 for discussion.
=> [Haskell] Clean up and bugfix of Haskell starter package

website/organizationWhitelist.txt
http://www.nationalresearch.com/
=> Add new company: NRC - National Research

airesources/OCaml/MyBot.ml, airesources/OCaml/README.md, airesources/OCaml/RandomBot.ml, airesources/OCaml/debug.ml, airesources/OCaml/halite.ml, airesources/OCaml/runGame.bat, airesources/OCaml/runGame.sh, airesources/OCaml/td.ml
Hi, would it be possible to add OCaml to the available languages?
If you would prefer the API to use camelCase rather than underscores and lowercase, I can change that. I've followed the OCaml convention since other users of the language are likely to prefer that, but I'm not partisan.
Also I've used 'row' and 'col' rather than 'y' and 'x' when dealing with map co-ordinates, since this more closely matches the internal representation, but again I can change it if you would prefer.
I've tested it offline and the basics seem to be working. I haven't thoroughly tested the get_distance and get_angle functions, but they should match the logic found in the Python starter.
Best regards,
=> add OCaml starter package

website/basics_intro_halite.php
=> Copy changes

airesources/Go/src/hlt/gamemap.go
Manhattan distance should be dx + dy not dx - dy
=> GetDistance improperly calculates the Manhattan distance

website/organizationWhitelist.txt
It would be great to have an additional university in the whitelist :)
=> Add RWTH Aachen to organization whitelist

website/organizationWhitelist.txt
=> Add Allstate to organizationWhitelist.txt

website/script/leaderTable.js, website/script/user.js
Add a tooltip when hovering over the score to show the underlying mu and sigma.
=> Add mu and sigma tooltip to leaderboard and user pages.

website/organizationWhitelist.txt
=> Update Organization Whitelist

tests/worker/languageBot/LANGUAGE, tests/worker/languageBot/MyBot.py, tests/worker/languageBot/hlt.py, tests/worker/languageBot/networking.py, tests/worker/languageBot/run.sh, tests/worker/testWorker.py, worker/compiler.py
If a LANGUAGE file is included in the bot zip file, the first line of it
will be used to override the displayed language used. It has no impact
on how the bot is compiled or run.
Closes #265
=> Allow LANGUAGE file to override displayed language

tests/environment/testenv.py, tests/install.sh
=> Fix java error on travis

website/api/web/WebsiteAPI.php, website/recent_games.php, website/script/recent_games.js
This adds a page that displays a live feed of games as they are completed.
While it displays the games with roughly the timing that they are completed on the server, it makes only one request per minute to the server. So it shouldn't cause heavy load on the server.
I would like to create a recent submissions page in a similar vein. But to do so in any sort of clean way would require adding a timestamp when a submission is made<sup>1</sup> to the database.
<sup>1</sup> or maybe better, when successfully compiled?
=> Add recent games page.

website/script/recent_games.js, website/script/status.js
Also always sort the users in a game on recent_games.
=> Fix date parsing on status and recent_games pages. 

airesources/Go/MyBot.go, airesources/Go/RandomBot.go, airesources/Go/src/hlt/networking.go
Timeout for 1st round is 15 seconds. This change allows bots written in
go to take advantage of that extra time.
=> Pull conn.sendName(...) logic out of NewConnection()

website/api/web/WebsiteAPI.php, website/script/recent_games.js, website/script/user.js
This adds rank, mu and sigma information for a user with a game query. It then displays the rank and username in a tooltip when hovering over the player icon in a game list.
=> Display user's name and rank in tooltip for player icon.

environment/core/hlt.hpp, tests/environment/testenv.py, tests/worker/testWorker.py, website/advanced_command_line.php, worker/worker.py
=> Add actual map size reporting.

visualizer/index.html, visualizer/lib/xss.js
Adds missing xss script to the electron visualizer setup.
=> Include xss script in electron visualizer.

website/api/manager/ManagerAPI.php
Pulls mu and sigma from the db instead of using the ones returned from our workers. Includes some related refactoring.
=> Closes #351

visualizer/index.html, visualizer/lib/xss.js, website/script/parsereplay.js
Palette taken from post in http://forums.halite.io/t/visualizer-is-not-color-blind-friendly/751/3 which comes from http://mkweb.bcgsc.ca/biovis2012/
=> Use a color blind safe palette in the visualizer.

airesources/Java/Direction.java, airesources/Java/GameMap.java, airesources/Java/Location.java, airesources/Java/MyBot.java, airesources/Java/Networking.java, airesources/Java/RandomBot.java, airesources/Java/Site.java
Reverts HaliteChallenge/Halite#363
=> Revert "Performance improvement for Java Starter Package: Got rid of object churn"

website/script/parsereplay.js
This improves game parsing speeds by 5 to 20 times and locally gets the time back to less than a second for most games.
=> Improve speed of game parsing.

airesources/Java/Direction.java, airesources/Java/GameMap.java, airesources/Java/Location.java, airesources/Java/MyBot.java, airesources/Java/Networking.java, airesources/Java/RandomBot.java, airesources/Java/Site.java
This PR is fixing the visibility issue with var production in Site (original PR was #363).
=> Performance improvement for Java Starter Package: Got rid of object churn + fixed production visibility

website/script/parsereplay.js
This fixes incorrect map strengths displayed in visualizer.
=> Stop indirect mutation of gameMap.

website/script/parsereplay.js
Fixes resetting all the cumulative graphs back to zero on the final frame.
=> Make the cumulative graphs, cumulative on the final frame.

visualizer/index.html, visualizer/index.js, website/local_visualizer.php, website/script/localVisualizer.js, website/script/visualizer.js
This allows you to either drag and drop another file or open the file selector after starting a replay in the local visualizers (both local_visualizer.php and the electron based one).
=> Allow loading another replay after starting one in the local visualizer

website/organizationWhitelist.txt
forgot to include them before >.>
=> Adding UoE students

website/script/parsereplay.js
It appears that currently the extended graphs are showing the state of the end of a frame rather than the start of frame state, essentially displaying everything one frame early.
=> Fix extended graph off by one error.

website/organizationWhitelist.txt
Added GVSU to organization whitelist
=> Add Grand Valley State University to whitelist

tests/install.sh
Attempt to fix the travis CI build.
=> Stick with old stable phpunit that will work with php 5.6.

website/api/web/WebsiteAPI.php, website/script/backend.js, website/script/status.js
This allows to easily check the current median mu and sigma. The sigma in particular will be nice to see during the finals.
=> Add median mu and sigma to status page.

website/api/manager/ManagerAPI.php
Add setting to stop game tasks being handed out.
Add setting to change to uniform seeding for the finals.
=> Changes to manager task api for finals.

website/api/web/WebsiteAPI.php, website/includes/navbar.php
Unfortunately since user account logins are hardcoded to the actual competition site, I haven't figured out a way to fully test this locally. The file doesn't throw a syntax error at least. ;)
=> Add option to close bot submissions.

admin/checkTaskCompletion.py
For use during transition to finals to ensure all compiles and games have completed.
=> Script to check for tasks completion.
